export const RENDER = 'RENDER'
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
export const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN'

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'
